### ISSUE TITLE
Определиться с требованиями к ПО. Что же хочет заказчик?

### ISSUE THREAD

**Issue by zantyru** [zantyru/wrk-QA21-first#1]
Если бы вы были заказчиком, то какие пожелания насчёт функциональных возможностей данного ПО? А как оно должно выглядеть?
(Не забываем про https://app.diagrams.net )

**Comment by BuslovI** [comment]
Попробуем

**Comment by RoCoS12** [comment]
Не надо пробовать, делать надо.
